"""
MITRE ATT&CK knowledge base — expanded to cover both document-based
and network-based attack techniques.

Each entry includes: name, description, tactic (kill chain stage),
impact, category, mitigation, and detection_method.
"""

MITRE_KB = {
    # ── Document Scanner Techniques ────────────────────────────
    "T1059": {
        "name": "Command and Scripting Interpreter",
        "description": "Adversaries may abuse command and script interpreters to execute commands, scripts, or binaries.",
        "impact": "Remote code execution, system compromise, lateral movement",
        "tactic": "Execution",
        "category": "Execution",
        "mitigation": "Restrict script execution policies, monitor command-line activity, use application whitelisting, disable unused scripting engines.",
        "detection_method": "Monitor process creation, command-line arguments, script execution logs, and unusual interpreter usage.",
    },
    "T1566": {
        "name": "Phishing",
        "description": "Adversaries may send phishing messages to gain access to victim systems, often via malicious attachments or links.",
        "impact": "Initial access, credential theft, malware delivery",
        "tactic": "Initial Access",
        "category": "Initial Access",
        "mitigation": "User training, email filtering, URL scanning, multi-factor authentication, sandboxing attachments.",
        "detection_method": "Monitor email gateways, analyze URLs and attachments, track user click behavior on suspicious links.",
    },
    "T1036": {
        "name": "Masquerading",
        "description": "Adversaries may manipulate features of their artifacts to make them appear legitimate or benign to users and security tools.",
        "impact": "Defense evasion, persistence, deception of security tools",
        "tactic": "Defense Evasion",
        "category": "Defense Evasion",
        "mitigation": "File integrity monitoring, code signing enforcement, process monitoring, block execution from suspicious paths.",
        "detection_method": "Compare file names vs expected locations, verify digital signatures, monitor for renamed system utilities.",
    },
    "T1003": {
        "name": "OS Credential Dumping",
        "description": "Adversaries may attempt to dump credentials from the operating system to obtain account login credentials.",
        "impact": "Credential access, lateral movement, privilege escalation",
        "tactic": "Credential Access",
        "category": "Credential Access",
        "mitigation": "Credential Guard, restrict access to LSASS, disable WDigest, use Protected Users group, limit admin privileges.",
        "detection_method": "Monitor access to LSASS process, SAM registry hive, NTDS.dit, and credential-related API calls.",
    },
    "T1110": {
        "name": "Brute Force",
        "description": "Adversaries may use brute force techniques to attempt access to accounts through systematic password guessing.",
        "impact": "Account compromise, unauthorized access, lateral movement",
        "tactic": "Credential Access",
        "category": "Credential Access",
        "mitigation": "Account lockout policies, MFA, strong password requirements, rate limiting, CAPTCHA on login endpoints.",
        "detection_method": "Monitor failed login attempts, unusual authentication patterns, login attempts from unusual locations.",
    },
    "T1056": {
        "name": "Input Capture / Shoulder Surfing",
        "description": "Adversaries may capture user input through keylogging, screen capture, or physical observation (shoulder surfing).",
        "impact": "Credential theft, data exposure, privacy violation",
        "tactic": "Collection",
        "category": "Collection",
        "mitigation": "Privacy screens, security awareness training, anti-keylogger software, screen lock policies, clean desk policy.",
        "detection_method": "Detect keylogger processes, monitor for screen capture APIs, physical security awareness programs.",
    },
    "T1499": {
        "name": "Endpoint Denial of Service",
        "description": "Adversaries may perform denial of service attacks to degrade or block availability of targeted resources.",
        "impact": "Service downtime, revenue loss, reputation damage",
        "tactic": "Impact",
        "category": "Impact",
        "mitigation": "Rate limiting, traffic filtering, CDN/DDoS protection services, resource monitoring, auto-scaling.",
        "detection_method": "Monitor network traffic volumes, connection rates, resource utilization, and unusual traffic patterns.",
    },
    "T1078": {
        "name": "Valid Accounts / Insider Threat",
        "description": "Adversaries or malicious insiders may use legitimate credentials to gain access, move laterally, or exfiltrate data.",
        "impact": "Data exfiltration, sabotage, unauthorized access, privilege abuse",
        "tactic": "Persistence",
        "category": "Initial Access / Persistence",
        "mitigation": "Least privilege access, behavior analytics (UEBA), DLP systems, separation of duties, exit process controls.",
        "detection_method": "User behavior analytics, off-hours access monitoring, unusual data access patterns, privilege escalation events.",
    },

    # ── Network IDS Techniques (UNSW-NB15) ─────────────────────
    "T1190": {
        "name": "Exploit Public-Facing Application",
        "description": "Adversaries may exploit vulnerabilities in internet-facing applications (web servers, databases, APIs) to gain initial access.",
        "impact": "Remote code execution, data breach, system compromise",
        "tactic": "Initial Access",
        "category": "Initial Access",
        "mitigation": "Patch management, WAF deployment, input validation, vulnerability scanning, network segmentation.",
        "detection_method": "Monitor web server logs for exploit signatures, IDS/IPS alerts, anomalous HTTP requests, error rate spikes.",
    },
    "T1046": {
        "name": "Network Service Scanning",
        "description": "Adversaries may scan for running services on remote hosts to identify attack surfaces and vulnerabilities.",
        "impact": "Information gathering, attack surface mapping, vulnerability identification",
        "tactic": "Discovery",
        "category": "Discovery",
        "mitigation": "Network segmentation, firewall rules, disable unnecessary services, port filtering.",
        "detection_method": "Monitor for sequential port connections, unusual SYN packets, IDS signatures for scanning tools (Nmap, Masscan).",
    },
    "T1210": {
        "name": "Exploitation of Remote Services",
        "description": "Adversaries may exploit remote services (SMB, RDP, SSH) to gain execution on remote systems for lateral movement.",
        "impact": "Lateral movement, remote code execution, privilege escalation",
        "tactic": "Lateral Movement",
        "category": "Lateral Movement",
        "mitigation": "Patch management, network segmentation, disable unnecessary remote services, MFA for remote access.",
        "detection_method": "Monitor authentication logs, unusual remote service usage, exploit signatures in network traffic.",
    },
    "T1071": {
        "name": "Application Layer Protocol",
        "description": "Adversaries may communicate using application layer protocols (HTTP, DNS, SMTP) to blend C2 traffic with normal traffic.",
        "impact": "Covert command and control, data exfiltration, persistent access",
        "tactic": "Command and Control",
        "category": "Command and Control",
        "mitigation": "Deep packet inspection, DNS sinkholing, SSL/TLS inspection, protocol-aware firewalls.",
        "detection_method": "Analyze DNS query patterns, HTTP beaconing intervals, unusual protocol usage, encrypted traffic analysis.",
    },
    "T1595": {
        "name": "Active Scanning",
        "description": "Adversaries may actively scan target infrastructure to gather information for targeting (IP ranges, open ports, services).",
        "impact": "Target profiling, vulnerability discovery, attack planning",
        "tactic": "Reconnaissance",
        "category": "Reconnaissance",
        "mitigation": "Rate limiting, honeypots, network monitoring, minimize exposed services.",
        "detection_method": "Monitor for high-rate connection attempts, sequential IP/port scanning patterns, honeypot interactions.",
    },
    "T1570": {
        "name": "Lateral Tool Transfer",
        "description": "Adversaries may transfer tools or malware between systems within a compromised network to facilitate lateral movement.",
        "impact": "Malware propagation, lateral movement, network-wide compromise",
        "tactic": "Lateral Movement",
        "category": "Lateral Movement",
        "mitigation": "Network segmentation, endpoint detection, file integrity monitoring, application whitelisting.",
        "detection_method": "Monitor SMB/file share transfers, unusual file creation on remote systems, known malware hash detection.",
    },
}
